//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int BankId { get; set; }
        public string BankName { get; set; }
        public string BankEname { get; set; }
        public string BankFullName { get; set; }
        public string BankShort { get; set; }
        public Nullable<int> CapitalType { get; set; }
        public Nullable<int> BankLevel { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> SwitchBack { get; set; }
        public int BankStatus { get; set; }
        public int CreatorId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
