//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NFMT_Basic_ConnectStr : DbContext
    {
        public NFMT_Basic_ConnectStr()
            : base("name=NFMT_Basic_ConnectStr")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Asset> Asset { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<BankAccount> BankAccount { get; set; }
        public virtual DbSet<BDStatus> BDStatus { get; set; }
        public virtual DbSet<BDStatusDetail> BDStatusDetail { get; set; }
        public virtual DbSet<BDStyle> BDStyle { get; set; }
        public virtual DbSet<BDStyleDetail> BDStyleDetail { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<BrandAsset> BrandAsset { get; set; }
        public virtual DbSet<ClauseContract_Ref> ClauseContract_Ref { get; set; }
        public virtual DbSet<ContractClause> ContractClause { get; set; }
        public virtual DbSet<ContractClauseDetail> ContractClauseDetail { get; set; }
        public virtual DbSet<ContractMaster> ContractMaster { get; set; }
        public virtual DbSet<CorpDept> CorpDept { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<DeliverPlace> DeliverPlace { get; set; }
        public virtual DbSet<Exchange> Exchange { get; set; }
        public virtual DbSet<FuturesCode> FuturesCode { get; set; }
        public virtual DbSet<FuturesPrice> FuturesPrice { get; set; }
        public virtual DbSet<MeasureUnit> MeasureUnit { get; set; }
        public virtual DbSet<Parameter> Parameter { get; set; }
        public virtual DbSet<PriceAuthority> PriceAuthority { get; set; }
        public virtual DbSet<Producer> Producer { get; set; }
        public virtual DbSet<Rate> Rate { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
