//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClauseContract_Ref
    {
        public int RefId { get; set; }
        public Nullable<int> MasterId { get; set; }
        public Nullable<int> ClauseId { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> IsChose { get; set; }
        public Nullable<int> RefStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    
        public virtual ContractClause ContractClause { get; set; }
        public virtual ContractMaster ContractMaster { get; set; }
    }
}
