//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractClause
    {
        public ContractClause()
        {
            this.ClauseContract_Ref = new HashSet<ClauseContract_Ref>();
            this.ContractClauseDetail = new HashSet<ContractClauseDetail>();
        }
    
        public int ClauseId { get; set; }
        public string ClauseText { get; set; }
        public string ClauseEnText { get; set; }
        public Nullable<int> ClauseStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    
        public virtual ICollection<ClauseContract_Ref> ClauseContract_Ref { get; set; }
        public virtual ICollection<ContractClauseDetail> ContractClauseDetail { get; set; }
    }
}
