//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractClauseDetail
    {
        public int ClauseDetailId { get; set; }
        public Nullable<int> ClauseId { get; set; }
        public Nullable<int> DetailDisplayType { get; set; }
        public Nullable<int> DetailDataType { get; set; }
        public Nullable<int> FormatSerial { get; set; }
        public string DetailValue { get; set; }
        public Nullable<int> DetailStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    
        public virtual ContractClause ContractClause { get; set; }
    }
}
