//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporationDetail
    {
        public int DetailId { get; set; }
        public Nullable<int> CorpId { get; set; }
        public string BusinessLicenseCode { get; set; }
        public Nullable<decimal> RegisteredCapital { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public string CorpProperty { get; set; }
        public string BusinessScope { get; set; }
        public string TaxRegisteredCode { get; set; }
        public string OrganizationCode { get; set; }
        public Nullable<bool> IsChildCorp { get; set; }
        public string CorpZip { get; set; }
        public Nullable<int> CorpType { get; set; }
        public Nullable<bool> IsSelf { get; set; }
        public string Memo { get; set; }
        public Nullable<int> DetailStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
