//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corporation
    {
        public int CorpId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string CorpCode { get; set; }
        public string CorpName { get; set; }
        public string CorpEName { get; set; }
        public string TaxPayerId { get; set; }
        public string CorpFullName { get; set; }
        public string CorpFullEName { get; set; }
        public string CorpAddress { get; set; }
        public string CorpEAddress { get; set; }
        public string CorpTel { get; set; }
        public string CorpFax { get; set; }
        public string CorpZip { get; set; }
        public Nullable<int> CorpType { get; set; }
        public Nullable<bool> IsSelf { get; set; }
        public int CorpStatus { get; set; }
        public int CreatorId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
