//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DeptId { get; set; }
        public int CorpId { get; set; }
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
        public string DeptFullName { get; set; }
        public string DeptShort { get; set; }
        public Nullable<int> DeptType { get; set; }
        public Nullable<int> ParentLeve { get; set; }
        public int DeptStatus { get; set; }
        public Nullable<int> DeptLevel { get; set; }
        public int CreatorId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
