//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_PledgeApply
    {
        public int PledgeApplyId { get; set; }
        public string PledgeApplyNo { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<System.DateTime> ApplyTime { get; set; }
        public Nullable<int> FinancingBankId { get; set; }
        public Nullable<int> FinancingAccountId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<bool> SwitchBack { get; set; }
        public Nullable<int> ExchangeId { get; set; }
        public Nullable<decimal> SumNetAmount { get; set; }
        public Nullable<int> SumHands { get; set; }
        public Nullable<int> PledgeApplyStatus { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastModifyId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
