//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_PledgeApplyCashDetail
    {
        public int CashDetailId { get; set; }
        public Nullable<int> PledgeApplyId { get; set; }
        public string StockContractNo { get; set; }
        public string Deadline { get; set; }
        public Nullable<int> Hands { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> ExpiringDate { get; set; }
        public string AccountName { get; set; }
        public string Memo { get; set; }
        public Nullable<int> DetailStatus { get; set; }
    }
}
