//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sm_SmsParameter
    {
        public int ParameterId { get; set; }
        public Nullable<int> SmsTypeId { get; set; }
        public string ParameterType { get; set; }
        public string ParamterValue { get; set; }
        public Nullable<int> ParameterStatus { get; set; }
        public Nullable<bool> IsType { get; set; }
    }
}
