//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sm_SmsType
    {
        public int SmsTypeId { get; set; }
        public string TypeName { get; set; }
        public string ListUrl { get; set; }
        public string ViewUrl { get; set; }
        public Nullable<int> SmsTypeStatus { get; set; }
        public string SourceBaseName { get; set; }
        public string SourceTableName { get; set; }
    }
}
