//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NFMT_Sms_ConnectStr : DbContext
    {
        public NFMT_Sms_ConnectStr()
            : base("name=NFMT_Sms_ConnectStr")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sm_Sms> Sm_Sms { get; set; }
        public virtual DbSet<Sm_SmsConfig> Sm_SmsConfig { get; set; }
        public virtual DbSet<Sm_SmsDetail> Sm_SmsDetail { get; set; }
        public virtual DbSet<Sm_SmsParameter> Sm_SmsParameter { get; set; }
        public virtual DbSet<Sm_SmsType> Sm_SmsType { get; set; }
    }
}
