//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wf_Node
    {
        public int NodeId { get; set; }
        public int MasterId { get; set; }
        public int NodeStatus { get; set; }
        public string NodeName { get; set; }
        public Nullable<int> NodeType { get; set; }
        public Nullable<bool> IsFirst { get; set; }
        public Nullable<bool> IsLast { get; set; }
        public Nullable<int> PreNodeId { get; set; }
        public Nullable<int> AuditEmpId { get; set; }
        public Nullable<int> AuthGroupId { get; set; }
        public Nullable<int> NodeLevel { get; set; }
    }
}
