//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wf_TaskOperateLog
    {
        public int LogId { get; set; }
        public int TaskNodeId { get; set; }
        public int EmpId { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public string LogResult { get; set; }
    }
}
