//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wf_TaskNode
    {
        public int TaskNodeId { get; set; }
        public int NodeId { get; set; }
        public int TaskId { get; set; }
        public Nullable<int> NodeLevel { get; set; }
        public Nullable<int> NodeStatus { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
    }
}
