//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NFMT_WorkFlow_ConnectStr : DbContext
    {
        public NFMT_WorkFlow_ConnectStr()
            : base("name=NFMT_WorkFlow_ConnectStr")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Wf_AuditEmp> Wf_AuditEmp { get; set; }
        public virtual DbSet<Wf_DataSource> Wf_DataSource { get; set; }
        public virtual DbSet<Wf_FlowMaster> Wf_FlowMaster { get; set; }
        public virtual DbSet<Wf_FlowMasterConfig> Wf_FlowMasterConfig { get; set; }
        public virtual DbSet<Wf_Node> Wf_Node { get; set; }
        public virtual DbSet<Wf_NodeCondition> Wf_NodeCondition { get; set; }
        public virtual DbSet<Wf_NodeOperate> Wf_NodeOperate { get; set; }
        public virtual DbSet<Wf_Task> Wf_Task { get; set; }
        public virtual DbSet<Wf_TaskAttach> Wf_TaskAttach { get; set; }
        public virtual DbSet<Wf_TaskAttachOperateLog> Wf_TaskAttachOperateLog { get; set; }
        public virtual DbSet<Wf_TaskNode> Wf_TaskNode { get; set; }
        public virtual DbSet<Wf_TaskOperate> Wf_TaskOperate { get; set; }
        public virtual DbSet<Wf_TaskOperateLog> Wf_TaskOperateLog { get; set; }
    }
}
